// <auto-generated />
using ApiAutomovel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiAutomovel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211026191126_vaiLaa")]
    partial class vaiLaa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiAutomovel.Models.Automovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("NumPortas")
                        .HasColumnType("int");

                    b.Property<int>("NumRodas")
                        .HasColumnType("int");

                    b.Property<string>("Placa")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("tipoCarro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Automeveis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "Branco",
                            Descricao = "Carro semi novo",
                            Modelo = "Ford Focus",
                            NumPortas = 4,
                            NumRodas = 4,
                            Placa = "asp-9823",
                            Preco = 30000m,
                            tipoCarro = 1
                        });
                });

            modelBuilder.Entity("ApiAutomovel.Models.TipoCarro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoVeiculo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("TipoCarro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TipoVeiculo = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            TipoVeiculo = "Picape"
                        },
                        new
                        {
                            Id = 3,
                            TipoVeiculo = "SUV"
                        },
                        new
                        {
                            Id = 4,
                            TipoVeiculo = "Esportivo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
